### ISSUE TITLE
Hover over top-right button

### ISSUE THREAD

**Issue by juri33** [ozdemirburak/jquery-floating-social-share#11]
Hi,

if i set the position to top-right and hover over the buttons the whole sidebar (all buttons) moves to left.
I would expect that only the hovered button get bigger and all other buttons stay on the same position.

**Comment by ozdemirburak** [comment]
@juri33 Thanks for reporting that, should've been resolved now.

**Comment by juri33** [comment]
@ozdemirburak awesome, nice work, appreciated
