### ISSUE TITLE
Remove Font Awesome Dependency

### ISSUE THREAD

**Issue by ozdemirburak** [ozdemirburak/jquery-floating-social-share#12]
Font awesome dependency can be removed with the usage of predefined inline svg with the help of the [simple-icons package](https://github.com/simple-icons/simple-icons/tree/develop/icons).

For instance, [network property, Facebook](https://github.com/ozdemirburak/jquery-floating-social-share/blob/master/src/jquery.floating-social-share.js#L89) can be extended like below where Facebook SVG can be found [here](https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/facebook.svg).

```js
"facebook" : {
  className: "facebook",
  icon: "<svg aria-labelledby='simpleicons-facebook-icon' role='img' viewBox='0 0 24 24' xmlns='http://www.w3.org/2000/svg'><title id='simpleicons-facebook-icon'>Facebook icon</title><path d='M22.676 0H1.324C.593 0 0 .593 0 1.324v21.352C0 23.408.593 24 1.324 24h11.494v-9.294H9.689v-3.621h3.129V8.41c0-3.099 1.894-4.785 4.659-4.785 1.325 0 2.464.097 2.796.141v3.24h-1.921c-1.5 0-1.792.721-1.792 1.771v2.311h3.584l-.465 3.63H16.56V24h6.115c.733 0 1.325-.592 1.325-1.324V1.324C24 .593 23.408 0 22.676 0'/></svg>",
  url:"https://www.facebook.com/sharer/sharer.php?u={url}&t={title}"
},
```

Then just [modify the source code](https://github.com/ozdemirburak/jquery-floating-social-share/blob/master/src/jquery.floating-social-share.js#L45) that it will use the icon property or whatever instead of the font awesome one.

**Comment by marioidival** [comment]
I can help you!
