### ISSUE TITLE
Fixes CSS

### ISSUE THREAD

**Issue by wallpageNET** [ozdemirburak/jquery-floating-social-share#14]
#floatingSocialShare a {     min-width: 45px; }

@media only screen and (min-device-width: 0px) and (max-width:961px) {
#floatingSocialShare a {     min-width: 45px; }
}

**Comment by wallpageNET** [comment]
Fixes the UG in Chrome... On the resize Event

**Comment by ozdemirburak** [comment]
I cant produce any errors with this, what is the error here?

**Comment by wallpageNET** [comment]
When i have the mobile Buttons on the bottom and i move/ resize/ rotate the window back to full width with the 45px buttons on the right the Buttons are still on prozent and they are very very small. 
With this you keep the buttons all the time on : #floatingSocialShare a { min-width: 45px; }
See it on http://www.wallpage.net/en

**Comment by ozdemirburak** [comment]
I see, but when there are many buttons, it would fail in mobile as the width is calculated by 100 / n where n is the count of buttons. So even the width is calculated, the minimum width would make it fail?

**Comment by wallpageNET** [comment]
For me it works now...on http://www.wallpage.net/en so it's  maybe a dirty fix...but with this it's absolut perfect what you have made... ;-) Thanks ! I will put your code into a wallpage plugin... maybe you can make a pro version later???

**Comment by ozdemirburak** [comment]
Thanks for your kind words :) But anyway, I'll take a look on the issue with on resize. I'm not currently thinking about that, but who knows, maybe in the future.
