### ISSUE TITLE
JavaScript (Maybe!?)

### ISSUE THREAD

**Issue by wallpageNET** [ozdemirburak/jquery-floating-social-share#15]
window.addEventListener("orientationchange", function() {
        setMobileCss(links);
        checkPlacePosition($child, base.settings.place, base.element, base.settings.extra_offset);
        updateIsMobile();	
}, false);
    }

**Comment by ozdemirburak** [comment]
I guess there is no need for this, as when orientation is changed, resize event is fired too?
