### ISSUE TITLE
Fontawsome

### ISSUE THREAD

**Issue by wallpageNET** [ozdemirburak/jquery-floating-social-share#16]
var places = ["content-left", "content-right", "top-left", "top-right"],
    networks = {
      "mail":  {
        icon: "<i class='fa fa-mail fa-2x' aria-hidden='true'></i>",
        url: "mailto:?subject={url}"
      },
      "facebook" : {
        icon: "<i class='fa fa-facebook fa-2x' aria-hidden='true'></i>",
        url:"https://www.facebook.com/sharer/sharer.php?u={url}&t={title}"
      },
      "google-plus": {
        icon: "<i class='fa fa-google-plus fa-2x' aria-hidden='true'></i>",
        url: "https://plus.google.com/share?url={url}"
      },
      "linkedin": {
        icon: "<i class='fa fa-linkedin fa-2x' aria-hidden='true'></i>",
        url: "https://www.linkedin.com/shareArticle?mini=true&url={url}&title={title}&summary={description}&source="
      },
      "odnoklassniki": {
        icon: "<i class='fa fa-odnoklassniki fa-2x' aria-hidden='true'></i>",
        url: "https://connect.ok.ru/dk?st.cmd=WidgetSharePreview&st.shareUrl={url}"
      },
      "pinterest":  {
        icon: "<i class='fa fa-pinterest fa-2x' aria-hidden='true'></i>",
        url: "https://pinterest.com/pin/create%2Fbutton/?url={url}&description={description}&media={media}"
      },
      "reddit": {
        icon: "<i class='fa fa-reddit fa-2x' aria-hidden='true'></i>",
        url: "https://www.reddit.com/submit?url={url}&title={title}"
      },
      "stumbleupon": {
        icon: "<i class='fa fa-stumbleupon fa-2x' aria-hidden='true'></i>",
        url: "https://www.stumbleupon.com/submit?url={url}&title={title}"
      },
      "telegram": {
        icon: "<i class='fa fa-telegram fa-2x' aria-hidden='true'></i>",
        url: "https://telegram.me/share/url?text={title}&url={url}"
      },
      "tumblr": {
        icon: "<i class='fa fa-tumblr fa-2x' aria-hidden='true'></i>",
        url: "https://www.tumblr.com/share/link?url={url}&name={title}&description={description}"
      },
      "twitter": {
        icon: "<i class='fa fa-twitter fa-2x' aria-hidden='true'></i>",
        url:"https://twitter.com/home?status={title}%20{url}"
      },
      "vk": {
        icon: "<i class='fa fa-vk fa-2x' aria-hidden='true'></i>",      
        url: "https://vk.com/share.php?url={url}&title={title}&description={description}"
      },
      "whatsapp": {
        icon: "<i class='fa fa-whatsapp fa-2x' aria-hidden='true'></i>",
        url: "whatsapp://send?text={title}%20{url}"
      }
    };

**Comment by wallpageNET** [comment]
Oh .. I see the people don't want this...

**Comment by ozdemirburak** [comment]
Yeah, it's better not to depend on any other project.
