### ISSUE TITLE
TypeError: v is undefined

### ISSUE THREAD

**Issue by metakel** [ozdemirburak/jquery-floating-social-share#17]
Caught this error and the social share bar does not show up:

TypeError: v is undefined
jquery.floating-social-share.min.js:1:4681

**Comment by ozdemirburak** [comment]
Can you give more details please? This log is not helping, use the source file instead of the minified one, and then please show how you called the plugin with what options like which buttons do you use etc.

**Comment by metakel** [comment]
Thank you. I have just changed to use the non-minified version under the "src" directory, but still got the same error.

I am using it in a Drupal 8 site with the below code to call the function. It was used from version 1.8.1. It works perfectly at version 1.8.1.

`(function ($, Drupal) {
  Drupal.behaviors.myModuleBehavior = {
    attach: function (context, settings) {
      
jQuery(".node--type-article .post-content .node__content").floatingSocialShare({
    place: "left", // alternatively content-left, content-right, top-right
    counter: true, // set to false for hiding the counters of buttons
    twitter_counter: false, // Twitter API does not provide counters without API key, register to https://opensharecount.com/
    buttons: ["envelope", "facebook", "google-plus", "linkedin", "pinterest", "twitter"], // all of the currently avalaible social buttons
    title: document.title, // your title, default is current page's title
    url: window.location.href,  // your url, default is current page's url
    text: {'default': 'share with ', 'facebook': 'share with facebook', 'google-plus': 'share with g+'}, // the title of tags
    text_title_case: false, // if set true, then will convert share texts to title case like Share With G+
    description: $('meta[name="description"]').attr("content"), // your description, default is current page's description
    media: $('meta[property="og:image"]').attr("content"), // pinterest media
    popup_width: 400, // the sharer popup width, default is 400px
    popup_height: 300 // the sharer popup height, default is 300px
});
  
    }
  };
})(jQuery, Drupal);`

**Comment by ozdemirburak** [comment]
Why did you close the issue, you found the problem? Also envelope is removed in v2.0, use mail instead.

**Comment by metakel** [comment]
I closed accidentally, sorry. I am reopening it.

**Comment by metakel** [comment]
Oh thank you, after I replaced "envelope" to "mail", it works.
