### ISSUE TITLE
rel='noopener'

### ISSUE THREAD

**Issue by anarchoi** [ozdemirburak/jquery-floating-social-share#19]
Hi,

Can you please add rel='noopener' to external links to fix Google Lighthouse errors like this: http://prntscr.com/iz6rda

https://developers.google.com/web/tools/lighthouse/audits/noopener

Thanks for the great plugin

**Comment by ozdemirburak** [comment]
Hi, thanks for bringing this issue, and sorry for the late reply. Just released a new version of the plugin that patches this issue.
