### ISSUE TITLE
Controlling pinterest share content

### ISSUE THREAD

**Issue by annKwilinski** [ozdemirburak/jquery-floating-social-share#2]
Hello,
I was wondering if I can add an image to the pinterest share button? right now it just shared my sites description. I have open graph tags that facebook and google plus share buttons acknowledges but id like to adjust the pinterest one. 
Thanks. 
-Ann

**Comment by ozdemirburak** [comment]
@annKwilinski Hi there, added the option that you can adjust the Pinterest media on the sharer's `media` tag. Just upgrade to the latest version, then you should be fine. 

If this doesn't solve solve your problem, don't hesitate to re-open this issue again.

Burak

**Comment by annKwilinski** [comment]
Works Great @ozdemirburak ! Thank you!
-Ann
