### ISSUE TITLE
Position left of main content

### ISSUE THREAD

**Issue by jonblack** [ozdemirburak/jquery-floating-social-share#3]
I'd really like to have the social buttons appear to the left of the main content. This is similar to `top-left` but instead of being `left: 0` (right against the edge of the browser), I'd like it to be to the left of the main content.

Below is an example taken from http://coschedule.com/blog/social-media-buttons/ (which uses a different share plugin).

![example](https://cloud.githubusercontent.com/assets/175080/13202035/e144d672-d88a-11e5-97e7-fe38f11fdf4a.png)

**Comment by ozdemirburak** [comment]
@jonblack thanks for the feedback, added this new feature, you can use it like below.

```
<body>
    <div class="content">
        Bla bla bla
    </div>
</body>

<script>
    $(".content").floatingSocialShare({
        buttons: ["facebook", "twitter", "google-plus"],
        text: "share with: ",
        place: "content-left"
    });
</script>
```
If you face with any further issues, don't hesitate to comment it out :)

**Comment by jonblack** [comment]
Nice job. I'll give this a go in the weekend. For completeness, it might be worth adding a `content-right` as well :smile:

**Comment by ozdemirburak** [comment]
Yeah, probably, will implement it on the weekend, as it needs more work on the css :)

**Comment by jonblack** [comment]
I've tested your change and it works great. I have to override `top: 25%` with the following:

```
.content-left {
    @media (min-width: 961px) {
        top: 131px !important;
    }
}
```

So on large devices it aligned with the top of the div and on mobile it has no effect.

Thanks!
