### ISSUE TITLE
Facebook and Google share not working

### ISSUE THREAD

**Issue by vedant12** [ozdemirburak/jquery-floating-social-share#5]
i have kept the url as windown.location.href but it isnt working as google and facebook are giving errors. Please can you fix this asap?

**Comment by ozdemirburak** [comment]
@vedant12 Are you sure you don't have a typo issue since it should be `window.location.href`, not `windown.location.href`.

If you don't have, then on what browser you have this issue?

**Comment by vedant12** [comment]
Hi @ozdemirburak no the there is no typo in my code, also i just figured out that the google and facebook share dosent work on localhost domain. If i hardcode my server name and try sharing , it works. 
Any Ideas?

**Comment by ozdemirburak** [comment]
That's the normal behaviour, they don't allow localhost as a callback url.

For further information, see [this](https://stackoverflow.com/questions/26021781/testing-facebook-share-dialog-with-localhost-unable-to-resolve-object-at-url) question and answers.

**Comment by vedant12** [comment]
@ozdemirburak  Thank you for the help , i just realized the scenario for localhost (still learning).
Thank you for the plugin it works great :)

**Comment by ozdemirburak** [comment]
Thanks :) 

Closing the issue, if you face with any errors again, just feel free to re-open another issue.

**Comment by vedant12** [comment]
Works like a charm
