### ISSUE TITLE
Console - Failed to load resource: net::ERR_NAME_NOT_RESOLVED

### ISSUE THREAD

**Issue by wraithseeker** [ozdemirburak/jquery-floating-social-share#6]
Thanks for this great and simple plugin but there's a small problem that I noticed occurring on the console.

Although it doesn't affect functionality, I would like to know how would I be able to remove this error?
`
Failed to load resource: net::ERR_NAME_NOT_RESOLVED - https://urls.api.twitter.com/1/urls/count.json?url=someurl`

**Comment by ozdemirburak** [comment]
Ah yes, Twitter has removed the functionality for checking the counters for a long time. 

I forgot to remove the twitter requests for checking counters, will fix it soon.

**Comment by ozdemirburak** [comment]
@wraithseeker Hello there, I've published a new release, by default, a parameter named `twitter_counter` is set to false, when it's set to true, it will let the plugin to check tweet count through [Open Share Count](https://opensharecount.com/) where you need to register if your pages are not indexed by someone's directives.

**Comment by wraithseeker** [comment]
I updated to the latest version but the CSS of the share buttons seem to be overlapping / not displaying properly.

For now I commented out the code that's causing the console error.

**Comment by ozdemirburak** [comment]
Can you share a screenshot please?

**Comment by wraithseeker** [comment]
Old version of the css file : http://puu.sh/oIsQw/d5117a3796.png

New version of the css file : http://puu.sh/oIsS9/b9e4151855.png

**Comment by ozdemirburak** [comment]
I've removed the global css rule, that should be the problem.

```
* {
    box-sizing: border-box;
}
```

But tested on Firefox and Chrome and seemed to work well, don't know why, which browser you are testing it on ?

**Comment by wraithseeker** [comment]
I am using a 13 inch Macbook on Chrome Version 50.0.2661.94 (64-bit)

**Comment by ozdemirburak** [comment]
What happens if you edit the main div's rules like below, 

```
#floatingSocialShare {
    box-sizing: border-box;
    position: relative;
}
```

**Comment by wraithseeker** [comment]
I went into the CSS and checked and it was these 4 lines that was causing the css problem after the update

```
#floatingSocialShare a
   width: 45px;
     height: 30px;
     line-height: 20px;
     padding: 8px 0;
```

**Comment by ozdemirburak** [comment]
Yes, they are the ones, because of the reason that I've removed the box-sizing rule as mentioned before in #4.

```
* {
    box-sizing: border-box;
}
```

Does the lines in my previous comment fix the problem?

**Comment by wraithseeker** [comment]
Yes it will fix the problem

**Comment by ozdemirburak** [comment]
Thank you very much :) fixing it asap.
